### ISSUE TITLE
Contribution guides

### ISSUE THREAD

**Issue by theaqua** [xPaw/CF-ABetterBrowser#58]
Hey, @xPaw, I think we need to add contribution guides for new languages. For example, what (new line in translations, new item in list, version) update and where (links to files).

**Comment by xPaw** [comment]
We sort of have a simple check list in README, but expanding on that would be a good idea. However I don't think updating version should be necessary. As for what line, do it in alphabetical order (leaving english always at top).

**Comment by xPaw** [comment]
I've updated readme, anything else that should be mentioned?

**Comment by theaqua** [comment]
You're right about version. I think everything is fine now.
