### ISSUE TITLE
Upload new version to Cloudflare

### ISSUE THREAD

**Issue by bluet** [xPaw/CF-ABetterBrowser#85]
The version of code on cloudflare is still at 2.0.4, can @xPaw or @TeffenEllis upload the latest version?

**Comment by xPaw** [comment]
I've submitted a new version, will go live once Cloudflare approves.

**Comment by bluet** [comment]
@xPaw it's still old version, 2.0.4

https://www.cloudflare.com/apps/XzVIEqe1R2kW/install
"You’re previewing A Better Browser 2.0.4 by Pavel Djundik & Eugene Rodionov."

![2019-03-01 12-00-19](https://user-images.githubusercontent.com/51141/53615597-a5802b00-3c19-11e9-84fe-cce7a75d07db.png)
